#define MOS_PIN 27

#define DEFAULT_BRIGHTNESS 150

#define WIFI_SSID "WIFI_SSID"
#define WIFI_PASS "WIFI_PASS"
#define HOSTNAME "HOSTNAME"

#define MQTT_HOST "MQTT_HOST"
#define MQTT_PORT 1883
#define MQTT_USER "MQTT_USER"
#define MQTT_PASS "MQTT_PASS"

#define MQTT_TOPIC_SET "TOPIC_NAME/set"
#define MQTT_TOPIC_STATE "TOPIC_NAME/state"